version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: container-pg-16.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend 
    container_name: node-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - .:/app
    command: npm start

volumes:
  pgdata:
